name: ADC website deployment [STAGE]
run-name: Deploy ADC website to STAGE [@${{ github.actor }}]

on:
  workflow_dispatch:

jobs:
  deploy-production:
    name: deploy
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: 'production-green'
      cloudfront-distribution-id: ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}
      s3-bucket: ${{ vars.S3_BUCKET }}
      s3-bucket-region: ${{ vars.S3_BUCKET_REGION }}
      web-domain: ${{ WEB_DOMAIN }}
