name: ADC website deployment [STAGE]
run-name: Deploy ADC website to STAGE [@${{ github.actor }}]

on:
  workflow_dispatch:

jobs:
  deploy-production:
    name: deploy
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      aliasRecordName: ADCWebStageARecord
      bucketName: ADCWebStageBucket
      cachePolicyName: ADCWebStageCachePolicy
      deploymentName: ADCWebStageDeployment
      distributionName: ADCWebStageDistribution
      domains: stage.ascensus.digital
      environment: production-green
      host: stage
      stackName: ADCWebStageStack
