name: ADC website deployment
run-name: Deploy ADC website [@${{ github.actor }}]

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: production

    steps:
      - name: Validate data
        run: |
          echo "Environment ${{ inputs.environment}}"
          echo "Tag: $GITHUB_REF_NAME"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add version file
        run: |
          VERSION_FILE=/home/runner/work/adc-website/adc-website/app/src/version.html
          VERSION=$GITHUB_REF_NAME
          NEW_CONTENT="<!DOCTYPE html><html lang=\"en\"><head><title>Version</title></head><body>Version: <strong>$VERSION</strong></body></html>"
          echo "VERSION_FILE: $VERSION_FILE"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "github.workspace: ${{ github.workspace }}"

          echo "$NEW_CONTENT" > $VERSION_FILE

      - name: Install dependencies
        run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Deploy application
        uses: reggionick/s3-deploy@v4
        with:
          folder: app/src
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /
          delete-removed: true
          no-cache: true
          private: true
          files-to-include: '{.*/**,**}'

  smoke-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: production
    needs: deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Smoke test
        run: bash app/test/scripts/smoke-test.sh https://ascensus.digital
