name: ADC website deployment
run-name: Deploy ADC website [@${{ github.actor }}]

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add version file
        run: |
          VERSION_FILE_NAME=version.json
          VERSION_FILE_PATH=${{ github.workspace }}/app/src/$VERSION_FILE_NAME
          VERSION=$GITHUB_REF_NAME
          NEW_CONTENT="{\"version\": \"$VERSION\"}"

          echo "$NEW_CONTENT" > $VERSION_FILE_PATH

      - name: Install dependencies
        run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::030460844096:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-west-1

      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity

      - name: Deploy application
        uses: reggionick/s3-deploy@v4
        with:
          folder: app/src
          bucket: ${{ vars.S3_BUCKET }}
          bucket-region: ${{ vars.S3_BUCKET_REGION }}
          dist-id: ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /
          delete-removed: true
          no-cache: true
          private: true
          files-to-include: '{.*/**,**}'

  smoke-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: production
    needs: deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Smoke test
        run: bash app/test/scripts/smoke-test.sh https://ascensus.digital
