name: Validate branch merge constraints
run-name: ${{ github.actor }} is validating merge constraints ${{ github.base_ref }}<--${{ github.head_ref }}

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          export TERM=xterm-256color
          ALLOWED_BRANCH="stage"

          echo GITHUB_BASE_REF = $GITHUB_BASE_REF
          echo GITHUB_HEAD_REF = $GITHUB_HEAD_REF
          echo ALLOWED_BRANCH = $ALLOWED_BRANCH

            if [[ $GITHUB_HEAD_REF != $ALLOWED_BRANCH ]]; then
              tput setaf 1
              echo Merging from \"$GITHUB_HEAD_REF\" to \"$GITHUB_BASE_REF\" is prohibited.
              exit 1
            else
              tput setaf 2
              echo Merging from \"$GITHUB_HEAD_REF\" to \"$GITHUB_BASE_REF\" is allowed.
              exit 0              
           fi
