name: Main Branch Protection

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          ALLOWED_BRANCH="stage"
          echo GITHUB_HEAD_REF = $GITHUB_HEAD_REF
          echo ALLOWED_BRANCH = $ALLOWED_BRANCH
          echo GIT_REFLOG_ACTION = $GIT_REFLOG_ACTION
            if [[ $GIT_REFLOG_ACTION != $ALLOWED_BRANCH ]]; then
              echo
              echo \#
              echo \# Merging from \"$ALLOWED_BRANCH\" to \"main\" is prohibited.
              echo \#
              echo
              exit 1
           fi
