name: Main Branch Protection

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          ALLOWED_BRANCH="stage"
          	if [[ $GITHUB_HEAD_REF != $ALLOWED_BRANCH ]]; then
          		echo
          		echo \# You may only merge to the main branch from the \"$ALLOWED_BRANCH\ branch"
          		echo
          		exit 1
          	fi
          fi
