name: Main Branch Protection

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          ALLOWED_BRANCH="stage"
          
          echo GITHUB_BASE_REF = $GITHUB_BASE_REF
          echo GITHUB_HEAD_REF = $GITHUB_HEAD_REF
          echo ALLOWED_BRANCH = $ALLOWED_BRANCH
          
            if [[ $GITHUB_HEAD_REF != $ALLOWED_BRANCH ]]; then
              echo
              echo \#
              echo \# Merging from \"$GITHUB_HEAD_REF\" to \"$GITHUB_BASE_REF\" is prohibited.
              echo \#
              echo
              exit 1
           fi
