name: Main Branch Protection

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          ALLOWED_BRANCH="stage"
          if [[ $GITHUB_HEAD_REF != $ALLOWED_BRANCH ]]; then
            echo
            echo \#
            echo \# Branch "main" may not be merged with branch \"$ALLOWED_BRANCH\"
            echo \#
            echo
            exit 1
          fi
